// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthorProfile: typeof import('./src/components/Author/Profile.vue')['default']
    AuthorSmall: typeof import('./src/components/Author/Small.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Giscus: typeof import('./src/components/Giscus.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PostCard: typeof import('./src/components/Post/Card.vue')['default']
    PostMeta: typeof import('./src/components/Post/Meta.vue')['default']
    PostNavigationArrows: typeof import('./src/components/Post/NavigationArrows.vue')['default']
    PostShare: typeof import('./src/components/Post/Share.vue')['default']
    PostTags: typeof import('./src/components/Post/Tags.vue')['default']
    ResumeEducation: typeof import('./src/components/Resume/Education.vue')['default']
    ResumeExpCard: typeof import('./src/components/Resume/ExpCard.vue')['default']
    ResumeExperience: typeof import('./src/components/Resume/Experience.vue')['default']
    ResumeProjects: typeof import('./src/components/Resume/Projects.vue')['default']
    ResumeTechnologies: typeof import('./src/components/Resume/Technologies.vue')['default']
    ResumeTechnologyCard: typeof import('./src/components/Resume/TechnologyCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Social: typeof import('./src/components/Social.vue')['default']
    UiBackToTop: typeof import('./src/components/Ui/BackToTop.vue')['default']
    UiColorSwitcher: typeof import('./src/components/Ui/ColorSwitcher.vue')['default']
    UiSpinner: typeof import('./src/components/Ui/Spinner.vue')['default']
  }
}
