name: Test build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 11
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install packages 📦
        run: pnpm install

      - name: Build site 🚧
        run: |
          pnpm build
          echo "✅ Gridsome site was built successfully"
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
